# Generated by Django 3.2.9 on 2022-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=80)),
                ('Phone_No', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=54)),
                ('Phone_No', models.CharField(max_length=11)),
            ],
        ),
    ]
