# Generated by Django 3.2.9 on 2022-03-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='Phone_No',
            field=models.CharField(max_length=80),
        ),
    ]
