# Generated by Django 3.2.9 on 2022-03-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0009_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
