# Generated by Django 3.2.9 on 2022-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0013_send_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_notification',
            name='message',
            field=models.TextField(),
        ),
    ]
