# Generated by Django 3.2.9 on 2022-03-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0014_alter_send_notification_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Send_Notification',
            new_name='Teacher_Notification',
        ),
    ]
