# Generated by Django 3.2.9 on 2022-03-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0020_attendance_attendance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SMS.teacher'),
        ),
    ]
