# Generated by Django 3.2.9 on 2022-03-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0026_student_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
