# Generated by Django 3.2.9 on 2022-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_alter_teachers_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claass',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
