# Generated by Django 3.2.9 on 2022-03-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
