# Generated by Django 3.2.9 on 2022-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_rename_send_notification_teacher_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
