# Generated by Django 3.2.9 on 2022-03-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0018_student_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_leave',
            old_name='datee',
            new_name='data',
        ),
    ]
