# Generated by Django 3.2.9 on 2022-03-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0021_course_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
