# Generated by Django 3.2.9 on 2022-03-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0023_alter_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='subject_id',
            new_name='course_id',
        ),
    ]
