# Generated by Django 3.2.9 on 2022-03-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0024_rename_subject_id_attendance_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LMS.course'),
        ),
    ]
